=== elainahowie/client-redesign/onestop.dtd
<!ELEMENT catalogue (course+)>
<!ELEMENT course (article, topic, description, author, campus, user)>
<!ATTLIST course subject (academics|finances|personal_information|how-toguides
|dates_deadlines| ) #REQUIRED>
<!ELEMENT article (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT campus (#PCDATA)>
<!ELEMENT user (#PCDATA)>

=== elainahowie/client-redesign/sections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "onestop.dtd">

<catalogue>

<!--Language-->
  <article subject="academics">
    <article>Class search resources</article>
    <topic subject= classes>Classes</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Take a class as a non-degree/guest Student-all</article>
    <topic subject= classes>Classes</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Senior Citizen Education Program</article>
    <topic subject= classes>Classes</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Registration times</article>
    <topic subject= classes>Classes</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Register for a class</article>
    <topic subject= classes>Classes</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>APAS</article>
    <topic subject= financial planning>Financial Planning</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Advising</article>
    <topic subject= financial planning>Financial Planning</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Graduation Planner</article>
    <topic subject= financial planning>Financial Planning</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Education requirements</article>
    <topic subject= financial planning>Financial Planning</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student-all</user>
  </article>

  <article subject="academics">
    <article>Change your major, minor, or college</article>
    <topic subject= financial planning>Financial Planning</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student</user>
  </article>

  <article subject="academics">
    <article>How to graduate in four years</article>
    <topic subject= financial planning>Financial Planning</topic>
    <description>Fill in description here!</description>
    <author>Goldy Gopher</author>
    <campus>All</campus>
    <user>Student</user>
  </article>

</catalogue>
